### ISSUE TITLE
Add support for `Windows`

### ISSUE THREAD

**Issue by CrazyboyQCD** [DouglasDwyer/mach-dxcompiler-rs#2]
Current download and decompress methods are not supported in Windows development, consider using crates to support it.
Like my script in https://github.com/DouglasDwyer/mach-dxcompiler-rs/issues/1.

**Comment by DouglasDwyer** [comment]
I am not sure what you mean by not supported - but there are a couple of issues with Windows builds to discuss:

- Windows builds rely on `curl.exe`/`tar.exe` in order to download and decompress files. These `exe`s are supposed to ship by default in Windows 10 and 11, but I'm not sure how ubiquitous they are. If they are missing from many users' systems, maybe we could ship them with the source code for this crate (assuming they are small utilities)? I really want to avoid using libraries like `reqwest` due to the heavy dependency chain; see my thoughts in #1.
- `msvc` builds are currently broken for `mach-dxcompiler`, which is unfortunate as `msvc` is the default target for Rust on Windows. To get around this, I am currently shipping a prebuilt binary from 2023 (the last one that had an `msvc` build). We should be able to figure out how to get MSVC working again (see https://github.com/hexops/mach/issues/1142)

Both of these are good things to think about - if you have any ideas, then please let me know.

**Comment by CrazyboyQCD** [comment]
> Windows builds rely on curl.exe/tar.exe in order to download and decompress files

That's why I closed this, I didn't know that windows has those tools before.

> To get around this, I am currently shipping a prebuilt binary from 2023 (the last one that had an msvc build). 

Api on this version is too simple to use.

> We should be able to figure out how to get MSVC working again

I am looking into CI now and see what I can do(building locally is too long and almost took up 100 percent cpu usage on my PC).

**Comment by DouglasDwyer** [comment]
Awesome! I am currently playing around with trying to get the latest version to build. I was able to successfully update the `msvc` target to build, but I am running into a new issue:

It seems like all of the prebuilt binaries link with the static MSVC CRT (`libcmt.lib`). This is causing a conflict when trying to build WGPU's tests, because WGPU has another native library that links with the dynamic MSVC CRT (`msvcrt.lib`). [It looks to me like the choice between static/dynamic CRT is hardcoded in the Zig build system, and is tied directly to whether you are building a `.lib` or `.dll`](https://github.com/ziglang/zig/blob/f845fa04a0dce3104efe129c73a6ad792b1712b6/src/link/Coff.zig#L2087-L2090). I want to emit a `.lib` and link the dynamic CRT, so I am not sure how to proceed :joy:

**Comment by CrazyboyQCD** [comment]
Better to open an issue, since it is hardcoded😂
